## dicomReadWrite.py
#
# The purpose of this module is to define functions related to DICOM read/write operations.
#

from asyncio.windows_events import NULL
from pydicom import dcmread, dcmwrite
import rootElem
import string
import __LOG.log as log
from datetime import datetime
from random import randint, choice
import os
from tkinter import messagebox # used to display a popup if there is a logging error (messagebox.showerror).
import sqlite3


## Connect to local DICOM Databases (this should be done during app initialization)
attributes = os.getcwd() + "\\db\\attributes.db"
db_attributes = sqlite3.connect(attributes)
cur_attributes = db_attributes.cursor()


## DICOM Static Variables
impClassUID = "1.2.7238.7553.751998.970815"  ## Unique Implementation Class UID for files generated by this program.


## Functions for Writing to Files
def create_dcm_file_dir():
    newFilePathDCM = os.getcwd() + "\\DICOM Files\\"
    if os.path.exists(newFilePathDCM):
        log.write_log_file(f"The file directory for DICOM files created by this program already exists: {newFilePathDCM}", 4)
    else:
        try:
            os.mkdir(newFilePathDCM)
            log.write_log_file(f"The file directory for DICOM files did not exist and has been created: {newFilePathDCM}", 4)
        except:
            messagebox.showerror("DICOM File Directory Error", f"The DICOM file directory at {newFilePathDCM} could not be created. Please check the file write permissions for the current Windows user.")
            log.write_log_file(f"The file directory at {newFilePathDCM} could not be created. New files will be created at {os.getcwd()}", 4)
            newFilePathDCM = os.getcwd()
    return newFilePathDCM


def dcm_file_write(dcmFile, dcmFilePath = None, overwrite = False):
    if overwrite and dcmFilePath != None:
        log.write_log_file(f"Overwriting existing DICOM files at {dcmFilePath} with new values.", 2)
    else:
        dcmFileDir_today = rootElem.newFilePathDCM + str(get_date_time()[0]) +"_" + str(get_date_time()[1])
        if overwrite and dcmFilePath == None:
            log.write_log_file("Requested to overwrite the existing DICOM file(s), but the file path was not passed. Creating new files instead.", 3)
        elif overwrite == False:
            log.write_log_file(f"Creating directory for the new DICOM files: {dcmFileDir_today}")
        os.mkdir(dcmFileDir_today)
        dcmFilePath = dcmFileDir_today


    if dcmFilePath != None:
        curFileIndex = 0
        for file in dcmFile:
            fileName = str(file[0x00080060].value) + "_" + str(file[0x00080050].value) + "_" + str(file[0x00080018].value) + ".dcm"  ## Modality_AccessionNumber_SOPInstanceUID.dcm
            folderName = str(file[0x00100020].value) + "_" + str(file[0x00100010].value) ## PatientID_PatientsName
            
            if isinstance(dcmFilePath, list) and ((len(dcmFilePath)-1) > curFileIndex): # if overwriting more than one file, quick check that number DICOM files matches number of paths provided. If not, write to dcmFileDir_today.
                path = dcmFilePath[0]
                log.write_log_file(f"More DICOM files were provided to overwrite than paths. Creating new file at {dcmFileDir_today}", 3)
                os.mkdir(dcmFileDir_today)
                path = dcmFileDir_today
            else:
                path = dcmFilePath + "\\"+ folderName
                if os.path.exists(path) == False:
                    os.mkdir(path)
                    log.write_log_file(f"Created the directory {path} to write the DICOM file(s) to.", 2)


            if overwrite and path != dcmFileDir_today:
                file.save_as(path)
                log.write_log_file(f"Updated the metadata within the following DICOM file: {dcmFilePath[curFileIndex]}", 6)
            else:
                path = path + "\\" + fileName
                with open(path, 'w') as newFileDcm:
                    pass
                dcmwrite(path, file)
                log.write_log_file(f"Created the DICOM file: {path}", 6)

            curFileIndex += 1
                


## Functions Used in DICOM Attribute Writing
def get_date_time():
    """
    Returns the current date and time, as well as the current date time.
    get_date_time()[0] = Current Date in YYMMDD format
    get_date_time()[1] = Current Time in HHmmSS format
    get_date_time()[2] = Current Date Time in UID format, so currentDate.CurrentTimeUID, 
                         where Current Time UID is in HHmmSSffffff format
    """
    currentDate = datetime.today().strftime('%Y%m%d')
    currentTime = datetime.today().strftime('%H%M%S')
    currentTimeUID = datetime.today().strftime('%H%M%S%f')
    currDateTimeUID = f"{currentDate}.{currentTimeUID}"
    return currentDate, currentTime, currDateTimeUID


def rand_int_as_str(length=8):
    randIntUID = ""
    for each in range(length):
        randIntUID = f"{randIntUID}{randint(0,9)}"
    if randIntUID[0] == '0':  ## In the event this value is used in a UID, the first value cannot be zero (https://dicom.nema.org/medical/dicom/current/output/html/part05.html#chapter_9)
        randIntUID = f"{randint(1,9)}" + randIntUID[1:]
    return randIntUID


## Base DICOM Functions
def read_files(dcmFilePath):
    if len(dcmFilePath) > 0:
        log.write_log_file("Reading DICOM files.", 6)
        log.write_log_file(f"Number of DICOM Files = {len(dcmFilePath)}", 6)
        dcmFile = [None] * len(dcmFilePath)
        try:
            for file in range(len(dcmFilePath)):
                dcmFile[file] = dcmread(dcmFilePath[file], force = True)
                log.write_log_file(f"Read DICOM contents of {dcmFilePath[file]} to 'dcmFile' array at index {file}", 6)
                if file == (len(dcmFilePath))-1:
                    log.write_log_file("All DICOM files have been read successfully.",6)
        except:
            log.write_log_file("Exception thrown when attempting to read DICOM files.", 3)
            dcmFile = [None]
    return dcmFile


def rand_UI(maxLength = 64, prefixImpClassUID = True):
    if prefixImpClassUID == True:
        prefixUID = impClassUID + "." + rand_int_as_str(5)
    else:
        randPrefixUID = "1.2." + f"{rand_int_as_str(3)}" + "." + f"{rand_int_as_str(5)}"
        prefixUID = randPrefixUID + "." + rand_int_as_str(5)
    randUID = prefixUID + "." + rand_int_as_str(8) + "." + get_date_time()[2]  ## add the current time at the end to reduce risk of this value matching any other value in the archive that may be used for testing.
    randUID = randUID[:maxLength]
    return randUID


def rand_PN():
    """
    Output an anonymized name in the DICOM format for the PN value representation
        randName = anonLast####^anonFirst####
    """
    randNum = rand_int_as_str(6)
    last = "anonLast" + randNum
    first = "anonFirst" + randNum
    randName = f"{last}^{first}"
    return randName


def rand_DA_TM_DT(yrsPast = 10, yrsFuture = 0):
    currYear = get_date_time()[0][:4]
    minYear = int(currYear) - yrsPast
    maxYear =  int(currYear) + yrsFuture
    randDA = f"{randint(minYear,maxYear)}" + "0101"
    randTM = f"{randint(00, 12):02d}" + "0000"
    randDT = randDA + randTM
    return randDA, randDT, randTM


def rand_SH_ST_LO_LT_UC_UT_AE(length = 12):
    char = string.ascii_letters + string.digits
    randVal = ""
    for each in range(length):
        randVal = f"{randVal}{choice(char)}"
    return randVal

def rand_CS():
    randVal = 'O'
    return randVal


def clean_tag_convention(dcmTag):
    removeVals = "(),[] .{}"
    removeValsTable = str.maketrans("", "", removeVals)
    dcmTag = str(dcmTag)
    dcmTag = dcmTag.translate(removeValsTable) ## If any of the chars match one of the chars in removeValsTable, delete them.
    return dcmTag


## DICOM Dictionaries
randomizeVal_perVR = {
    'PN': [rand_PN],
    'DA': [rand_DA_TM_DT, 0], ## for DA, return the first item in the tuple (index 0).
    'DT': [rand_DA_TM_DT, 1], ## for DT, return the second item in the tuple (index 1).
    'TM': [rand_DA_TM_DT, 2], # for TM, return the third item in the tuple (index 2).
    'UI': [rand_UI],
    'SH': [rand_SH_ST_LO_LT_UC_UT_AE],
    'ST': [rand_SH_ST_LO_LT_UC_UT_AE],
    'LO': [rand_SH_ST_LO_LT_UC_UT_AE],
    'LT': [rand_SH_ST_LO_LT_UC_UT_AE],
    'UC': [rand_SH_ST_LO_LT_UC_UT_AE],
    'UT': [rand_SH_ST_LO_LT_UC_UT_AE],
    'AE': [rand_SH_ST_LO_LT_UC_UT_AE],
    'CS': [rand_CS]}
## Remaining:  AS, AT, DS, IS, 


## DICOM functions called in conjunction with the Base DICOM Functions
def anonymize_data(dcmFilePath):
    """
    https://dicom.nema.org/medical/dicom/current/output/chtml/part15/chapter_e.html
    """
    dcmFile = read_files(dcmFilePath)
    if dcmFile != [None]:
        for file in range(len(dcmFile)):
            log.write_log_file(f"Starting anonymization of file {file+1}: {dcmFilePath[file]}", 2)
            ds = dcmFile[file]
            for element in dcmFile[file]:
                val = element.value
                vr = element.VR
                tag = clean_tag_convention(element.tag)
                cur_attributes.execute(f"SELECT anon FROM attributes WHERE tag = '{tag}'")
                anonVal = cur_attributes.fetchone()
                if anonVal == None: # Sql query did not return anything. Since this is probably a private tag, delete it.
                    del ds[tag]
                    log.write_log_file(f"Could not find tag in attributes.db: {tag} ({vr}). Deleting attribute with value [{val}]. ", 3)
                else:
                    if anonVal[0] != None: # Sql query returned that this tag has a corresponding anonymization action code.
                        if anonVal[0] != 'X' and vr != 'SQ':
                            """
                            Normally, you should choose to either delete or repalce to maintain IOD conformity.
                            I do not have time to review all IODs to have a way to map required tags to IODs. So...
                            Unless it explicitely states to remove tag (denoted by singular action code X), just randomize the value.
                            """
                            if vr in randomizeVal_perVR.keys():    
                                if len(randomizeVal_perVR[vr]) > 1:
                                        func = randomizeVal_perVR[vr][0]
                                        returnValIndex = randomizeVal_perVR[vr][1]
                                        element.value = func()[returnValIndex]
                                else:
                                    element.value = randomizeVal_perVR[vr][0]()
                                log.write_log_file(f"Replacing value [{val}] in tag {tag} ({vr}) with {element.value}", 6)
                        else:
                            del ds[tag]
                            if vr == 'SQ':
                                log.write_log_file(f"Deleted attributes {tag} ({vr}) and all nested sequence tags during anonymization.", 6)
                            else:
                                log.write_log_file(f"Deleted attribute {tag} ({vr}) during anonymization.", 6)
            else:
                log.write_log_file(f"Anonymization of DICOM File complete: {dcmFilePath[file]}\n", 2)
    else:
        log.write_log_file("Could not successfully read the DICOM files, therefore, they will not be anonymized.", 3)
        messagebox.showerror("Anonymization Error", "Could not anonymize the DICOM files since they could not be read. Please verify the .dcm files selected are in DICOM format.")
    
    dcm_file_write(dcmFile = dcmFile, dcmFilePath = dcmFilePath, overwrite = False) ## Create or override the DICOM files with the anonymized data.

    return dcmFile